### PR TITLE
collapse directives to 3 basic cases

### PR DESCRIPTION
**Pull request by jeffweiss**
### Summary of changes

I'll review the commits, so I mostly want to understand the "why" rather than the "what"

### Checklist

- [x] New functions have typespecs, changed functions were updated
- [x] Same for documentation, including moduledocs
- [x] Tests were added or updated to cover changes
- [x] Commits were squashed into a single coherent commit

Prior to this commit the directive were extremely repetitive without a
great deal of value and, in some cases, hiding the relationship between
the Directive type and the related Parser function. This commit distills
the directives into 3 basic cases:
* Directive type == Parser function
* Directive type != Parser function
* Directive type != Parser function, add zulu flag

Although none currently exist, if we encounter a case that does not fit
any of these 3 scenarios, then we can add it as a special case.

@bitwalker, if you feel like this doesn't make it easier to read or maintain, feel free to close/wont-merge. This made it easier for _me_ to reason about it, but I'm not sure it's a universal improvement.

### CODE REVIEW

**Comment by jeffweiss** [comment]
@bitwalker it looks like coverage only decreased the 90 line reduction in file size. :-/

**Comment by jeffweiss** [comment]
I'll need to rebase after the merge of #147 :smiley: standby...

**Comment by bitwalker** [comment]
Actually I really like this, it bothered me a bit that there was so much duplication there, but never enough where I took the time to refactor it. I think the coverage change is due to the fact that the uncovered lines now represent a greater percentage of the total lines of code, which I think is what you were saying, but yeah, not an issue.

Let me know when you want me to go ahead and merge :)

**Comment by jeffweiss** [comment]
@bitwalker go for it :+1:

**Comment by bitwalker** [comment]
Thanks!

**Pull request merged**
